services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - ./data/vaultwarden:/data:rw
    restart: always
#    ports:
#      - 8880:80
    environment:
      DOMAIN: '${DOMAIN}'
      SIGNUPS_ALLOWED: '${SIGNUPS_ALLOWED}'
#      SIGNUPS_DOMAINS_WHITELIST: '${SIGNUPS_DOMAINS_WHITELIST}'
      SIGNUPS_VERIFY: '${SIGNUPS_VERIFY}'
      REQUIRE_DEVICE_EMAIL: '${REQUIRE_DEVICE_EMAIL}'
      INVITATIONS_ALLOWED: '${INVITATIONS_ALLOWED}'
      SHOW_PASSWORD_HINT: '${SHOW_PASSWORD_HINT}'
      EMAIL_CHANGE_ALLOWED: '${EMAIL_CHANGE_ALLOWED}'
      ADMIN_TOKEN: '${ADMIN_TOKEN}'
      DISABLE_ADMIN_TOKEN: '${DISABLE_ADMIN_TOKEN}'
      SENDS_ALLOWED: '${SENDS_ALLOWED}'
      EMERGENCY_ACCESS_ALLOWED: '${EMERGENCY_ACCESS_ALLOWED}'
      ROCKET_PORT: '1024'

      # ORGANIZATIONS
      ORG_EVENTS_ENABLED: '${ORG_EVENTS_ENABLED}'
      ORG_GROUPS_ENABLED: '${ORG_GROUPS_ENABLED}'
#      EVENT_CLEANUP_SCHEDULE: '${EVENT_CLEANUP_SCHEDULE}'

      # Mail Server
#      SMTP_HOST: '${SMTP_HOST}'
#      SMTP_FROM: '${SMTP_FROM}'
#      SMTP_FROM_NAME: '${SMTP_FROM_NAME}'
#      SMTP_PORT: '${SMTP_PORT}'
#      SMTP_SECURITY: '${SMTP_SECURITY}'
#      SMTP_USERNAME: '${SMTP_USERNAME}'
#      SMTP_PASSWORD: '${SMTP_PASSWORD}'
#      SMTP_EMBED_IMAGES: '${SMTP_EMBED_IMAGES}'

      # Logging
      LOG_FILE: '/data/vaultwarden.log'
      LOG_LEVEL: '${LOG_LEVEL}'
#      USE_SYSLOG: '${USE_SYSLOG}'
#      EXTENDED_LOGGING: '${EXTENDED_LOGGING}'

      # YubiKey authentication
#      YUBICO_CLIENT_ID: '${YUBICO_CLIENT_ID}'
#      YUBICO_SECRET_KEY: '${YUBICO_SECRET_KEY}'
#      YUBICO_SERVER: '${YUBICO_SERVER}'

#    networks:
#      - vaultwarden-net
    network_mode: service:tailscale-vault
    depends_on:
      - tailscale-vault


  borgmatic-vault:
    image: ghcr.io/borgmatic-collective/borgmatic
    container_name: borgmatic-vault
#    hostname: borgmatic-vault
    restart: always
    volumes:
      - ./data/vaultwarden:/mnt/source
      - borg-config-vol-1:/root/.config/borg
      - borg-cache-vol-1:/root/.cache/borg
      - ./data/borgmatic:/etc/borgmatic.d:Z
      - ./data/borgmatic/ssh:/root/.ssh:Z
    environment:
      - TZ=Europe/Vienna
      - BORG_PASSPHRASE=>>>>RANDOMCHARACTERS<<<<
#    networks:
#      - vaultwarden-net
    network_mode: service:tailscale-vault
    depends_on:
      - tailscale-vault

  tailscale-vault:
    image: tailscale/tailscale
    container_name: tailscale-vault
    hostname: vaultwarden
   # command: sh -c "tailscale serve reset"
    environment:
      - TS_AUTHKEY=tskey-auth-xxxx
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/vault.json
    volumes:
      - ./data/tailscale/state:/var/lib/tailscale
      - ./data/tailscale/config:/config
      - /dev/net/tun:/dev/net/tun
   # entrypoint: ./data/tailscale/config/cron.sh
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
#    networks:
#      - vaultwarden-net
    network_mode: host

volumes:
  vw-data:
    driver: local
  vaultwarden-tailscale:
    driver: local
  borg-cache-vol-1:
  borg-config-vol-1:
