services:
  passbolt-tailscale:
    image: tailscale/tailscale
    container_name: passbolt-tailscale
    hostname: passbolt
    environment:
      - TS_AUTHKEY=tskey-auth-xxx
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--accept-routes
      - TS_ROUTES=172.10.0.0/16
      - TS_DEBUG_FIREWALL_MODE=auto
    volumes:
      - ./data/tailscale/state:/var/lib/tailscale
      - ./data/tailscale/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  passbolt-db:
    image: mariadb:10.11
    container_name: passbolt-db
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      - database_volume:/var/lib/mysql
    network_mode: service:passbolt-tailscale

  passbolt:
    image: passbolt/passbolt:latest-ce
    container_name: passbolt
    restart: unless-stopped
    depends_on:
      - passbolt-db
    environment:
      APP_FULL_BASE_URL: https://passbolt.tailxxx.ts.net
      DATASOURCES_DEFAULT_HOST: "localhost"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "P4ssb0lt"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
      DATASOURCES_DEFAULT_PORT: "3306"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "localhost:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    network_mode: service:passbolt-tailscale

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
